# Generated by Django 3.2.4 on 2021-06-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Doctor',
            field=models.CharField(choices=[('Dr1', 'Doctor1'), ('Dr2', 'Doctor2')], max_length=3),
        ),
    ]
